### ISSUE TITLE
[Color] Feedback on color palette

### ISSUE THREAD

**Issue by mollieru** [18F/usfwds#261]
![colors](https://cloud.githubusercontent.com/assets/3680494/9070818/b28f4308-3abf-11e5-9ff9-ee1de5fa8f56.png)

**Comment by mollieru** [comment]
Feedback from @molliebates:

-          Have you used this tool? You pop in all your colors and test for passing.
-          I’m concerned about your blue for links. It fails on every color field, so you could never have a link in a well or on a sidebar. Consider making it darker to comply.
-          With so many blues available, I’m not sure why you have another row in “secondary colors”. Perhaps go more purple or orange to provide something different?
-          The yellow is not accessible with white, so you couldn’t use it with like an exclamation point in a circle, for example.
-          We’ve been nerding out on palettes lately, check it out.

**Comment by juliaelman** [comment]
@angel @mollieru can this be closed or are there outstanding questions?

**Comment by juliaelman** [comment]
Closing issue, as feedback has been completed and the work is in progress.
