### ISSUE TITLE
Weird scrolling behavior on iPhone, iPad

### ISSUE THREAD

**Issue by maya** [18F/usfwds#275]
When viewing the site on my iPhone 5, the scroll doesn't work properly. It feels kind of stiff, not sure if there is some scroll hijacking going on due to JS.

@carodew also mentioned experiencing some strange behavior as well.

**Comment by juliaelman** [comment]
@carodew @maya would one of you mind testing out some video recording of this interaction? Using either with an desktop emulator or a video camera to display what you mean by "weirdness" :)

**Comment by maya** [comment]
This is a video to indicate the issue which is also experienced on desktop: 

http://cl.ly/cFNv

**Comment by maya** [comment]
Is this related to momentum based scrolling? Overflow?

**Comment by carodew** [comment]
Adding a preview of a video showing the scrolling behavior. I think it's a momentum-based scrolling issue (not sure). On other websites, a swipe up or down with a finger will result with the scroll 'easing out' for a second or so after the swipe finishes. On our site the scrolling stops immediately when the swipe ends, making it feel throttled. 

iPhone 6 running iOS 8.4, Safari (not sure which version). 

https://drive.google.com/a/gsa.gov/file/d/0B1Wf-KSFneMUSWU0TXhoMGJwMlU/view?usp=sharing

**Comment by maya** [comment]
cc @vgvg

**Comment by maya** [comment]
This may have something to do with we are scrolling within a div as opposed to a page.

.main-content has an overflow: auto

<img width="261" alt="screen_shot_2015-08-25_at_11 35 53_am" src="https://cloud.githubusercontent.com/assets/5249443/9475830/11a844ac-4b1e-11e5-88a6-eecac6bce175.png">

So when you scroll the content, you are scrolling within that div. We'd need to remove all that, make the nav position: fixed, and change how the page is laid out.

**Comment by colinpmacarthur** [comment]
I replicated this behavior on an iPad 2 running iOS 8.4.

**Comment by vgvg** [comment]
PR #399 should have fixed this.

**Comment by sujithuix** [comment]
Add `-webkit-overflow-scrolling: touch;` to the scroll div. The scroll will become smooth then.
