### ISSUE TITLE
text cursor position doesn't stay where it should within the input field (iPhone 6 running iOS 8.4)

### ISSUE THREAD

**Issue by carodew** [18F/usfwds#277]
Steps to recreate: 

1. Have an iPhone 6 running iOS 8.4 
2. Insert the cursor into a text field. This puts focus on the field and triggers the mobile keyboard to appear. 
3. Scroll up an down on the page. The cursor will visually stay in the same spot even as the elements on the page move with the scroll. 

![iphone-screenshot1](https://cloud.githubusercontent.com/assets/10144074/9184365/ba18d338-3f82-11e5-82d4-2fcb7e6f5b69.PNG)

**Comment by maya** [comment]
@carodew is this on all input fields or just that component?

**Comment by carodew** [comment]
It's on all text input fields.

**Comment by carodew** [comment]
Here's a video showing the behavior: https://drive.google.com/open?id=0B1Wf-KSFneMUQWk0TTB4eElveE0

**Comment by vgvg** [comment]
This appears to be a bug with Safari on iOS itself. Found some references to similar behavior: https://bugs.webkit.org/show_bug.cgi?id=138201

It seems to be a symptom of having an input box inside of a container with overflow set to scroll. I was able to replicate the bug with just a very basic div with overflow: scroll, and an input in the middle of it and have not been able to find any clean css ways to fix it.

The two ways that would work to remove this bug are to remove the use of overflow scrolling on the main body of the page and either 1) have the header be sticky some other way, 2) let the header scroll along with the page on iOS. Are these options something we would want to do?

**Comment by maya** [comment]
@vgvg awesome, thanks! I agree that changing the header to sticky and changing the way the page is laid out is a good possible solution. I may look into this today.

I think this is also related to #275, so changing this may knock out both bugs.

**Comment by vgvg** [comment]
@maya yeah I just looked at that bug, changing overflow on a container and using the entire page's scrolling would help fix #275

**Comment by colinpmacarthur** [comment]
Replicated this bug on iPad 2 running iOS 8.4

**Comment by vgvg** [comment]
PR #399 should have fixed this one.

**Comment by carodew** [comment]
Received a request to access the video. Since I can't share the original video directly, here's a gif. Note that this issue has been resolved, I'm just providing it for the curious. 

![runaway cursor iphone 1](https://cloud.githubusercontent.com/assets/10144074/10730897/2baaa17a-7bc9-11e5-9f0f-5c2b4e49aeb5.gif)

**Comment by psr1919plus21** [comment]
For those, who still have related problem: 
This bug occur when input nested into parent with `position: fixed`.
Changing position to `absolute` resolved this problem for me.

**Comment by litsazib** [comment]
i already fix this problem 👍 please user this code ...
html,body{ -webkit-overflow-scrolling : touch !important; overflow: auto !important; height: 100% !important; }

**Comment by purvishah165** [comment]
-webkit-overflow-scrolling : touch !important; not working in iOS 11. It disabled user to scroll. Did anyone face the same problem?

**Comment by ZohidSB** [comment]
Scroll down and notice how the cursor also moves past the border of the text box,
![img_0457](https://user-images.githubusercontent.com/37531498/37584817-c65990c6-2b78-11e8-9a74-646d2cfafe3a.PNG)

**Comment by maya** [comment]
@ZohidSB what site is the image coming from?

**Comment by dotrajesh** [comment]
Insert the cursor into a text field. This puts focus on the field and triggers the mobile keyboard to appear.
Not Issue fixed

**Comment by NorhanSamir** [comment]
I've the same cursor problem and I cant fix it on ipad and iphone any help?!

**Comment by denveloperj** [comment]
@NorhanSamir you need to remove the `position:fixed` that maybe on your parent container.

**Comment by merbin2012** [comment]
Conclusion: All the Apple product is very worst.
