### ISSUE TITLE
Button classes don't work on <a> elements

### ISSUE THREAD

**Issue by jeremiak** [18F/usfwds#286]
There are some really cool button classes in the library (i.e. `usa-button-big`) but the classes don't work properly if applied to an element that isn't a `<button>`. I want to apply these button appearance classes to `<a>` elements so that I can easily use the UI component to go to another page.

Here are some screenshots, where the classes applied to the element are `usa-button-outlined usa-button-big` and only the element type is changed:

0. Using a `<button>` element: http://up.jeremiak.com/cDna
0. Using a `<a>` element: http://up.jeremiak.com/cDtI

Currently, my workaround is to use a JavaScript event handler to change the document location `onClick`

**Comment by maya** [comment]
Fixed via #302.

**Comment by maya** [comment]
Quick test on making our buttons anchor links and this is what it looks like:

![screen shot 2015-08-17 at 6 41 08 pm](https://cloud.githubusercontent.com/assets/5249443/9320470/67fd9c54-450f-11e5-9017-39342efc15bd.png)

cc @msecret

**Comment by maya** [comment]
Update: we must add `usa-button` class to anchor links in addition to the specific button class, but this is not needed for buttons. 

@msecret says it's possible to refactor and use @extend instead to remove this requirement but not a priority atm and this would be something to add in for the future.
