### ISSUE TITLE
Grid should have a setting for full screen pages

### ISSUE THREAD

**Issue by msecret** [18F/usfwds#328]
The grid currently has a max width of like 980 px. While this is often good, there are times when a site will want to take advantage of the full screen. An example:

http://www.smashingmagazine.com/

It might be helpful to have a mode like this.

**Comment by maya** [comment]
If you just use a div without the grid class, it becomes full-width. You can even add the grid inside any div and style the parent div however you like, taking advantage of full-width.

**Comment by msecret** [comment]
Yea agreed, I actually didn't even know that worked. Awesome to hear though

**Comment by maya** [comment]
Cool, closing this... I'm doing that for the homepage if you want to check it out too.
