### ISSUE TITLE
Header hiding/showing interferes with scrolling when keyboard is visible (iPhone 6, iOS 8.4)

### ISSUE THREAD

**Issue by colinpmacarthur** [18F/usfwds#344]
As iPhone 6 users scroll up the pattern library (on Safari), the header appears and impedes their scrolling. When it disappears, users can scroll again. See this video: https://drive.google.com/a/gsa.gov/file/d/0B1Wf-KSFneMUNDV3dktrbWJldmc/view

**Comment by vgvg** [comment]
Saw this in the simulator as well. Feels like an artifact of the overflow scrolling on the container. Might be fixed by PR #383.

**Comment by carodew** [comment]
@colinpmacarthur will retest!

**Comment by colinpmacarthur** [comment]
Open question: Physically prevents from scrolling or is just strange?

**Comment by colinpmacarthur** [comment]
Looks like PR #383 was superseded by PR #399. I tested #399 on my iPhone 6, iOS 8.4 and it seems to have fixed the problem.

When @vgvg merges #399 to staging, I think we can close this issue. I'm going to assign this issue back to him.

**Comment by vgvg** [comment]
Should be fixed now.
