### ISSUE TITLE
[Address Form] ZIP code triggers text, not number, soft keyboard. (multiple devices)

### ISSUE THREAD

**Issue by colinpmacarthur** [18F/usfwds#355]
Tapping the ZIP code triggers text soft keyboard. Ideally, the number soft keyboard would appear instead.

Screenshot of issue: 
![wrong keyboard for zip](https://cloud.githubusercontent.com/assets/2092076/9496632/47ca0cca-4bdf-11e5-8676-4259659f047b.png)

# Devices
- iPhone 6, iOS 8.4
- Moto E, Android 4.4, Chrome 44
- Samsung S5, Android 5 Lollipop, Chrome

**Comment by carodew** [comment]
@jpyuda you have been flagged to add what the thing should be.

**Comment by jpyuda** [comment]
The zip code field should be `type="text"` (browsers will drop leading zeroes if it is type number, and there are valid zip codes with leading zeroes). We can force the number keypad to come up by including this attribute: `pattern="\d{5,5}(-\d{4,4})?"`

**Comment by carodew** [comment]
I just tested this today and validation is working on the field, except it is showing a five-digit zip as invalid. 

Both 5-digit and 9-digit zips should be valid inputs. 

**Invalid input with five-digit ZIP**

<img width="149" alt="screen shot 2015-09-03 at 2 13 20 pm" src="https://cloud.githubusercontent.com/assets/10144074/9666793/41d896e8-5246-11e5-9c5a-d57dcc030866.png">

**Tested on**
Macbook Pro
Yosemite 10.10.5
Firefox 39.0.3
staging

**Comment by jpyuda** [comment]
I can't get it to do any validation on staging. Odd.

**Comment by carodew** [comment]
@jpyuda Maybe it's how Firefox handles HTML5 validation?

**Comment by jpyuda** [comment]
I'll bet that's it. I'll download FF and hack around.
