### ISSUE TITLE
[Alerts] Icons are not aligned with text at small screen sizes (multiple devices) 

### ISSUE THREAD

**Issue by colinpmacarthur** [18F/usfwds#356]
Screenshot of the problem on iOS:
![alerts iphone](https://cloud.githubusercontent.com/assets/2092076/9496894/8acd5b5c-4be0-11e5-87c2-7f13864bcb1d.PNG)

Screenshot of the problem on Android:
![alerts with mismatched icons](https://cloud.githubusercontent.com/assets/2092076/9496924/a5ed2cfa-4be0-11e5-8bd5-9c9b0d526ee3.png)

## Devices
- iPhone 6, iOS 8.4
- Moto E, Android 4.4, Chrome 44

**Comment by maya** [comment]
@colinpmacarthur this was a style issue and resolved on the latest PR of style tweaks. See staging for updated alerts.
