### ISSUE TITLE
Cannot tab focus to submit button on iPhone on mulitple forms.

### ISSUE THREAD

**Issue by carodew** [18F/usfwds#357]
When using the next/previous buttons on the iPhone soft keyboard to move focus from one form field to the next, the submit button is skipped. This button should be able to receive focus. 

Affects: 
* sign in form
* password reset form 
* contact us form 
* newsletter sign up form (in footer) 

Observed on: 
Apple iPhone 6, iOS 8.4, Safari
Apple iPad 2, iOS 8.4, Safari

**Comment by carodew** [comment]
Unclear if this is how it is supposed to work in Safari on iPhone – maybe it is supposed to be that if you hit 'Enter' anywhere in the form it triggers submit. Need more research to define the intended behavior.

**Comment by carodew** [comment]
Update: I have no idea how to research this. I did some Google searches but I don't really know what I'm looking for.

**Comment by mollieru** [comment]
@jpyuda can you take the lead on this?

**Comment by jpyuda** [comment]
This is the expected behavior of mobile safari on iOS. I don't recommend building functionality to override it.
