### ISSUE TITLE
[Dropdown]: More than one dropdown icon appears on the dropdown box on Moto E, Chrome

### ISSUE THREAD

**Issue by carodew** [18F/usfwds#358]
Moto E:

![dropdown with strange icon](https://cloud.githubusercontent.com/assets/10144074/9499171/c8103e02-4beb-11e5-8ae0-4f7434110679.png)

Could be a Chrome issue since I have the same problem on my Macbook in Chrome: 

<img width="956" alt="screen shot 2015-08-26 at 12 10 27 pm" src="https://cloud.githubusercontent.com/assets/10144074/9499144/a237612e-4beb-11e5-85fa-83bcaf8d85c1.png">

Observed on: Motorola Moto E, Android 4.4.4 Kitkat, Chrome 44
Macbook Pro, Chrome 44

**Comment by carodew** [comment]
@maya @colinpmacarthur We checked in staging and it looks like this may have been fixed, can you confirm or check?

**Comment by maya** [comment]
This was resolved in #376
