### ISSUE TITLE
[Text Input Field] on Moto E: If you are entering text into a form field and change orientation, your browser scrolls way up the page.

### ISSUE THREAD

**Issue by carodew** [18F/usfwds#360]
If you are entering text into a form field and change orientation, your browser scrolls way up the page.

Observed on Motorola Moto E, Android 4.4.4 Kitkat, Chrome 44

**Comment by carodew** [comment]
@colinpmacarthur did you get a video of this behavior?

**Comment by msecret** [comment]
Can we check if theres something specific about our site that's causing this? Or does this happen on most sites?

**Comment by colinpmacarthur** [comment]
@msecret and @carodew: I've verified that this happens on all sites on this device. Closing this issue.
