### ISSUE TITLE
[Sign in form]: password field should not auto-capitalize on mobile 

### ISSUE THREAD

**Issue by carodew** [18F/usfwds#367]
When tapping on the password field in the sign in form, the soft keyboard switches it's capitalization to uppercase and the first letter typed is capitalized. It shouldn't. 

Observed on: 
Apple iPhone 6, iOS 8.4, Safari

**Comment by vgvg** [comment]
I couldn't reproduce when the field is masked, but was able to when clicking the "Show me what I'm typing" buttons.
