### ISSUE TITLE
[Side navigation ]Different items in mobile and desktop sidebar nav.

### ISSUE THREAD

**Issue by colinpmacarthur** [18F/usfwds#372]
At narrow screen sizes, "Home" and "About" links appear in the slide out sidebar navigation. Those links do not appear in the sidebar navigation at larger screen sizes.

On desktop:
<img width="241" alt="screen shot 2015-08-26 at 4 50 44 pm" src="https://cloud.githubusercontent.com/assets/2092076/9505831/a025122e-4c12-11e5-8b25-3fbc564403a3.png">

On mobile:
<img width="244" alt="screen shot 2015-08-26 at 4 51 19 pm" src="https://cloud.githubusercontent.com/assets/2092076/9505839/b0dbe62e-4c12-11e5-8077-a6459ad9f03a.png">

According to the design files, Home and About should appear in neither.

**Comment by carodew** [comment]
Need to define what the correct solution is.

**Comment by carodew** [comment]
@mollieru any progress on this?

**Comment by mollieru** [comment]
Resolution: the sidenav should *not* include links to 'Home' or 'About' (which does not exist)

**Comment by maya** [comment]
There's a new sidebar nav - I don't think this problem exists anymore.
