### ISSUE TITLE
[Side navigation] Hamburger icon does not appear on Moto E, Android 4.4, Chrome 44

### ISSUE THREAD

**Issue by colinpmacarthur** [18F/usfwds#385]
The hamburger icon next to the word "menu" in the header does not appear on Moto E, Android 4.4, Chrome 44.

**No hamburger icon on the Moto E:**
![screenshot_2015-08-27-18-16-47](https://cloud.githubusercontent.com/assets/2092076/9548166/f8772b96-4d6c-11e5-85ec-95e2cb5e41f6.png)

**Correct hamburger icon on the iPhone 6:**
![img_0116](https://cloud.githubusercontent.com/assets/2092076/9548210/2b7fe262-4d6d-11e5-993d-ec0c804fdf1a.PNG)

**Comment by mollieru** [comment]
Original design does not include hamburger. Hold on this as we may need to remove hamburger all together.

![screen shot 2015-08-28 at 10 34 01 am](https://cloud.githubusercontent.com/assets/3680494/9549888/4d7cfb1c-4d76-11e5-8c74-24dd5e36e39c.png)
![screen shot 2015-08-28 at 10 34 09 am](https://cloud.githubusercontent.com/assets/3680494/9549894/5217bb62-4d76-11e5-8f1d-60248a958a30.png)

**Comment by colinpmacarthur** [comment]
@mollieru: Good catch. 

Should I:
- close this issue because the sidebar nav is still being implemented?
- leave it open, but change it to be about removing the hamburger icon from the desktop version?

**Comment by mollieru** [comment]
@colinpmacarthur let's close for now. I made a note in the Trello card.
