### ISSUE TITLE
[Side Nav] Opened menu should push content to the right not overlay 

### ISSUE THREAD

**Issue by mollieru** [18F/usfwds#386]
This applies both to the Site sidenav as well as the component. 

Here's the current interaction:
http://screencast-o-matic.com/watch/coju2xfp4E

Here's the intended interaction:
http://screencast-o-matic.com/watch/coju2Ufp4g

Original designs for reference:

![screen shot 2015-08-28 at 10 34 01 am](https://cloud.githubusercontent.com/assets/3680494/9548805/8efaba94-4d70-11e5-860f-b776677609b6.png)
![screen shot 2015-08-28 at 10 34 09 am](https://cloud.githubusercontent.com/assets/3680494/9548811/95cff96a-4d70-11e5-96f4-1196bca312af.png)

**Comment by carodew** [comment]
Was this specified in the original feature? If not, shouldn't it be added as a new story in Trello, and not a bug?

**Comment by mollieru** [comment]
@carodew good point! will remove and add to the Trello card for this item (which is already in there).

**Comment by carodew** [comment]
As long as the Trello card isn't already in development. If so, we should not be making changes to it. If it's in development I think this should be a new card in the backlog.
