### ISSUE TITLE
[Search bar] Capital letters, ascenders, and descenders are cut off within the medium and small search bars in Firefox

### ISSUE THREAD

**Issue by carodew** [18F/usfwds#417]
**Steps to replicate**

In Firefox, type into the medium or small search bar. Capital letters, ascenders and descenders are cut off. 

![image](https://cloud.githubusercontent.com/assets/10144074/9671414/befab146-5260-11e5-8a90-374e84013417.png)

**Expected behavior**

Letters should be fully visible. 

**Tested on**
Macbook Pro
Yosemite 10.10.5
Firefox 39.0.3
staging

**Comment by maya** [comment]
TODO: look into how line height is being set on small and medium search bar inputs.

**Comment by maya** [comment]
@carodew resolved in #492.

**Comment by carodew** [comment]
lgtm! closing.
