### ISSUE TITLE
[Text links] Text links don't show visible focus styling in Firefox

### ISSUE THREAD

**Issue by carodew** [18F/usfwds#421]
**Steps to recreate**

Navigate to https://pages-staging.18f.gov/usfwds/visual-style/#links

Set focus on one of the text links. No different visual styling appears. 

**Expected behavior**

Would expect a blue halo around the link to indicate that it has focus. I checked in Chrome and it renders appropriately, just not showing up in Firefox. 

**Tested on**
Macbook Pro
Yosemite 10.10.5
Firefox 39.0.3
staging

**Comment by maya** [comment]
@carodew we do not have focus states for text links. Should we? If so, @angel can you give us the design or expected behavior you would like.

**Comment by maya** [comment]
@carodew fixed in https://github.com/18F/usfwds/pull/476. Can you please test and confirm?

**Comment by carodew** [comment]
lgtm – I checked in Chrome and FF. Closing the issue!
