### ISSUE TITLE
[Side navigation] Focus state is a dotted gray line instead of a blue halo in IE 11

### ISSUE THREAD

**Issue by carodew** [18F/usfwds#443]
**Steps to Recreate**

Open the site in IE 11. Tab through the site to set focus. Focus appears as a dotted gray line. 

<img width="194" alt="screen shot 2015-09-08 at 12 54 45 pm" src="https://cloud.githubusercontent.com/assets/10144074/9741517/d34c609c-5628-11e5-90f5-73c1f8f86ee3.png">

<img width="609" alt="screen shot 2015-09-08 at 1 45 17 pm" src="https://cloud.githubusercontent.com/assets/10144074/9742708/e461963e-562f-11e5-9990-00a89357279f.png">

**Expected behavior**

I would expect the focus state to be a blue halo, as it appears in Chrome. 

<img width="240" alt="screen shot 2015-09-08 at 12 55 24 pm" src="https://cloud.githubusercontent.com/assets/10144074/9741526/e50dc53c-5628-11e5-92b2-d0ca350f2fb1.png">

**Tested on**
IE 11
Windows 10
SauceLabs

**Comment by jpyuda** [comment]
Related to #447

**Comment by maya** [comment]
Related to https://github.com/18F/usfwds/issues/421 - we don't have a focus state defined for text links, so browsers are implementing their own defaults. Resolving #421 will resolve this.

**Comment by jpyuda** [comment]
Our prioritization on the focus-state items was based on an (incorrect) assumption that we had implemented a custom one. I'm going to re-tag these as "to be triaged" to revisit tomorrow.

**Comment by maya** [comment]
@jpyuda correct, we have a focus state implemented on inputs and buttons. But we never defined the state for anchor links. Sounds good!

**Comment by jpyuda** [comment]
Can somebody with access to IE11 test this?

**Comment by carodew** [comment]
Looks good!
