### ISSUE TITLE
[Site Navigation] When I first load the site, all the pages appear concatenated into one long scroll

### ISSUE THREAD

**Issue by carodew** [18F/usfwds#451]
**Steps to recreate**

![nav concatenation](https://cloud.githubusercontent.com/assets/10144074/9748235/79df58a6-5651-11e5-95e5-1a3e285025b4.gif)

1. Load the page https://pages-staging.18f.gov/usfwds/ . You will see the "Getting Started" section of the design standards. 
2. Scroll down. All the sections appear on the page in one long scroll. 
3. Click on any link in the side nav. Now the pages appear separate, as they should. 

 **Expected behavior**
Upon landing on "getting started" you would only see the "getting started" content and the rest of the standards would appear on separate pages, as outlined in the iA doc (and how they appear after clicking on any of the side nav items). 

 **Tested in**

IE11, Windows 10
Chrome

**Comment by maya** [comment]
@carodew this is not going to be an issue when we add the home page. I vote to close this. Feel free to check out the add homepage branch and review: https://github.com/18F/usfwds/pull/306

**Comment by maya** [comment]
@carodew this is solved on the current site. cc @jpyuda

**Comment by carodew** [comment]
Looks good.
